// Mã quyền THẬT lấy từ @PreAuthorize trong BE (Phase 1).
export const P = {
  USER_VIEW: 'USER_VIEW', USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE', USER_DELETE: 'USER_DELETE',
  USER_ASSIGN_WAREHOUSE: 'USER_ASSIGN_WAREHOUSE',
  ROLE_VIEW: 'ROLE_VIEW', ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE', ROLE_DELETE: 'ROLE_DELETE',
  PERMISSION_VIEW: 'PERMISSION_VIEW', PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE', PERMISSION_DELETE: 'PERMISSION_DELETE',
  WAREHOUSE_VIEW: 'WAREHOUSE_VIEW', WAREHOUSE_CREATE: 'WAREHOUSE_CREATE',
  WAREHOUSE_UPDATE: 'WAREHOUSE_UPDATE', WAREHOUSE_DELETE: 'WAREHOUSE_DELETE',
  MASTER_PRODUCT_VIEW: 'MASTER_PRODUCT_VIEW', MASTER_PRODUCT_MANAGE: 'MASTER_PRODUCT_MANAGE',
  MASTER_PARTNER_MANAGE: 'MASTER_PARTNER_MANAGE',
  INBOUND_VIEW_PO: 'INBOUND_VIEW_PO', INBOUND_CREATE_PO: 'INBOUND_CREATE_PO',
  INBOUND_APPROVE_PO: 'INBOUND_APPROVE_PO',
  INBOUND_VIEW_GRN: 'INBOUND_VIEW_GRN', INBOUND_CREATE_GRN: 'INBOUND_CREATE_GRN',
  INBOUND_COMPLETE_GRN: 'INBOUND_COMPLETE_GRN',
  NOTIF_READ: 'NOTIF_READ',
}
